version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2004:3000"
      - "2003:3001" 
    restart: always
    environment:
      - VITE_API_URL=http://10.2.10.17:3001
      - NODE_ENV=production
      - HTTPS=true
    networks:
      - app_network

networks:
  app_network:
    driver: bridge