version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2005:3000"
    restart: always
    environment:
      - VITE_API_URL=http://10.2.10.17:3001
      - NODE_ENV=production
      - HTTPS=true
    networks:
      - app_network 
    volumes:
      - /mnt/realtime-app-database:/mnt/realtime-app-database

networks:
  app_network:
    driver: bridge