version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2005:3000"
    restart: always
    environment:
      - VITE_API_URL=http://10.2.10.17:3001
      - NODE_ENV=production
      - HTTPS=true
    networks:
      - app_network 
    volumes:
      - /mnt/realtime-app-database:/mnt/realtime-app-database
    labels:
                - "traefik.enable=true"
                - "traefik.http.routers.frontend.rule=Host(`api.grupotapajos.com.br`)" 
                - "traefik.http.routers.frontend.entrypoints=web,websecure"
                - "traefik.http.routers.frontend.tls.certresolver=leresolver"
                - "traefik.http.routers.frontend.service=frontend"
                - "traefik.http.services.frontend.loadbalancer.server.port=3000"


networks:
  app_network:
    driver: bridge