version: '3.9'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "2004:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - .:/app
    command: ["npm", "start"]
